#! /usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('Star Trek 50th Anniversary Tweets | Database Populator', '0.2.0');

$app->add(new App\Console\PopulateDatabaseCommand());

$app->run();
